### ISSUE TITLE
module extraction guidelines

### ISSUE THREAD

**Issue by abierman** [netmod-wg/rfc6087bis#11]
Need guidelines for YANG modules and examples.
Do not use CODE BEGINS for examples

**Comment by abierman** [comment]
added text to Module Copyright section:

Note that this convention MUST NOT be used for example modules
or module fragments.

[FIXME: should a new convention called <EXAMPLE BEGINS>
be added for YANG example modules?]

**Comment by abierman** [comment]
Added text about using pyang:

*\* Validation Tools

All modules need to be validated before submission in
an Internet Draft. The 'pyang' YANG compiler is
freely available from github:

   https://github.com/mbj4668/pyang

If the 'pyang' compiler is used, then the "--ietf" command line
option SHOULD be used to identify any IETF guideline issues.

**Comment by abierman** [comment]
Added section on module extraction tools listing the yang-central
version of rfcstrip.

**Comment by mjethanandani** [comment]
In addition to the fact that example YANG models should not be surrounded by CODE BEGINS and CODE ENDS, the following error message should be ignored/suppressed for example YANG modules.

example-xyz-alarms.yang:1: error: IETF rule (RFC 6087: 4.7): statement "module" must have a "contact" substatement
example-xyz-alarms.yang:1: error: IETF rule (RFC 6087: 4.7): statement "module" must have a "organization" substatement

If keywords such as "contact" and "organization" are present in the module, they will be validated for correctness.

Finally, the example YANG module should compile, and any error/warnings will be flagged.

**Comment by abierman** [comment]
stable for 2 releases
