### ISSUE TITLE
RFC 2119 keywords within YANG modules

### ISSUE THREAD

**Issue by bclaise** [netmod-wg/rfc6087bis#19]
We should say a few words about "RFC 2119 keywords within YANG modules". Valid? Invalid? If valid, what does it mean? I don't think it should be different than MIB modules, which allows RFC 2119 keywords in object description IIRC.

**Comment by abierman** [comment]
add to sec. 4.5

Note that all YANG statements within a YANG module are considered
normative, if the module itself is considered normative,
and not an example module.  The use of keywords defined in ^RFC2119^
apply to YANG description statements in normative modules 
exactly as they would in any other normative section.

Example YANG modules MUST NOT contain any normative text,
including any reserved words from ^RFC2119^.

**Comment by abierman** [comment]
closed in draft-05
