### ISSUE TITLE
YANG model specified by other SDO

### ISSUE THREAD

**Issue by bclaise** [netmod-wg/rfc6087bis#22]
Carl Moberg volunteered to write a section on the URN.
Do we have any other advice?

**Comment by mjethanandani** [comment]
Relevant sections of 6087 need to updated to reflect YANG models being developed in other SDOs.

For example, Section 4.7 says:

   The organization statement MUST be present.  If the module is
   contained in a document intended for Standards Track status, then the
   organization SHOULD be the IETF working group chartered to write the
   document.

This could be made SDO neutral.

Similarly, in the same section, you have:

   The description statement MUST be present.  The appropriate IETF
   Trust Copyright text MUST be present, as described in Section 3.1.

**Comment by mjethanandani** [comment]
Section 4.8 is IETF specific. It should just say that upfront in that section.

**Comment by abierman** [comment]
changed IETF only text as follows:

The contact statement MUST be present.
If the module is contained in a document
intended for Standards Track status, then
the working group web and mailing information
MUST be present, and the main document author or
editor contact information SHOULD be present.
If additional authors or editors exist,
their contact information MAY be present.
In addition, the Area Director and other contact
information MAY be present.

The description statement MUST be present.
For modules published within IETF documents,
the appropriate IETF Trust Copyright text MUST be present,
as described in ^MODULECOPY^.

**Comment by abierman** [comment]
closed in draft-05
