### ISSUE TITLE
Tree guidelines

### ISSUE THREAD

**Issue by bclaise** [netmod-wg/rfc6087bis#39]
There are some guidelines already in the draft. This is good. However, a couple of points.
- Section 4.3. I would help the reader and provide "pyang -f tree <module.yang>"
- If the module is composed of groupings only, include the output of pyang -f tree --tree-print-groupings <module.yang> . Actually, should we always include the groupings in the draft?
- I'm not clear on the notification guidelines? Include or not? Should pyang be updated to produce the right output?
- What if the YANG tree diagrams guidelines change in the future? Should we include the output of pyang that generate this output?

Regards, B.

**Comment by abierman** [comment]
Issue fixed in draft-12
